@extends('layouts.app')
@section('title', $consumable->name)
@section('breadcrumb')<span class="text-gray-400">/</span><a href="{{ route('consumables.index') }}" class="hover:text-gray-800">Consumables</a><span class="text-gray-400">/</span><span class="text-gray-700 font-medium">{{ $consumable->name }}</span>@endsection
@section('content')
@php
    $usageHistory = $consumable->workOrderItems->map(fn($usage) => ['date' => $usage->used_at, 'qty' => $usage->qty_used, 'source' => 'Work Order', 'reference' => $usage->workOrder?->wo_number, 'title' => $usage->workOrder?->title, 'url' => $usage->workOrder ? route('work-orders.show', $usage->workOrder) : null, 'user' => $usage->createdBy?->name])->merge($consumable->maintenanceRecordConsumables->map(fn($usage) => ['date' => $usage->created_at, 'qty' => $usage->qty_used, 'source' => 'Maintenance Record', 'reference' => $usage->maintenanceRecord?->record_number, 'title' => $usage->maintenanceRecord?->workOrder?->title, 'url' => $usage->maintenanceRecord ? route('maintenance-records.show', $usage->maintenanceRecord) : null, 'user' => $usage->maintenanceRecord?->technician?->name]))->sortByDesc('date');
@endphp
<div class="max-w-4xl space-y-5">
    <div class="flex items-center gap-3"><a href="{{ route('consumables.index') }}" class="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg"><svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg></a><div><h1 class="text-2xl font-bold text-gray-900">{{ $consumable->name }}</h1><p class="text-sm text-gray-500">{{ $consumable->item_code }} · {{ $consumable->category ?: 'Consumable' }}</p></div></div>
    <div class="bg-white rounded-xl border border-gray-200 shadow-sm p-6"><div class="grid grid-cols-2 sm:grid-cols-4 gap-4"><div><dt class="text-xs font-medium text-gray-500 uppercase">Stok Aktual</dt><dd class="mt-1 text-lg font-bold {{ $consumable->qty_actual <= $consumable->qty_minimum ? 'text-orange-600' : 'text-emerald-600' }}">{{ $consumable->qty_actual }} {{ $consumable->unit }}</dd></div><div><dt class="text-xs font-medium text-gray-500 uppercase">Minimum</dt><dd class="mt-1 text-sm text-gray-900">{{ $consumable->qty_minimum }} {{ $consumable->unit }}</dd></div><div><dt class="text-xs font-medium text-gray-500 uppercase">Supplier</dt><dd class="mt-1 text-sm text-gray-900">{{ $consumable->supplier ?: '—' }}</dd></div><div><dt class="text-xs font-medium text-gray-500 uppercase">Lokasi</dt><dd class="mt-1 text-sm text-gray-900">{{ $consumable->location ?: '—' }}</dd></div></div>@if($consumable->description)<p class="mt-5 pt-4 border-t border-gray-100 text-sm text-gray-700">{{ $consumable->description }}</p>@endif</div>
    <div class="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden"><div class="px-5 py-4 border-b border-gray-100 flex items-center justify-between"><div><h2 class="font-semibold text-gray-900">Usage History</h2><p class="text-xs text-gray-500 mt-0.5">Riwayat pemakaian consumable.</p></div><span class="px-2 py-1 rounded-full bg-emerald-50 text-emerald-700 text-xs font-bold">{{ $usageHistory->sum('qty') }} {{ $consumable->unit }}</span></div>@if($usageHistory->isEmpty())<p class="py-10 text-center text-sm text-gray-400">Belum ada histori pemakaian.</p>@else<div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-gray-50 text-xs font-semibold text-gray-500 uppercase"><th class="px-5 py-3 text-left">Tanggal</th><th class="px-5 py-3 text-left">Sumber</th><th class="px-5 py-3 text-left">Referensi</th><th class="px-5 py-3 text-left">Qty</th><th class="px-5 py-3 text-left">Oleh</th></tr></thead><tbody class="divide-y divide-gray-50">@foreach($usageHistory as $usage)<tr><td class="px-5 py-3 text-gray-600">{{ $usage['date']?->format('d M Y H:i') }}</td><td class="px-5 py-3 text-gray-600">{{ $usage['source'] }}</td><td class="px-5 py-3 font-medium">@if($usage['url'])<a href="{{ $usage['url'] }}" class="text-brand hover:underline">{{ $usage['reference'] }}</a>@else{{ $usage['reference'] ?: '—' }}@endif @if($usage['title'])<span class="block text-xs text-gray-400">{{ $usage['title'] }}</span>@endif</td><td class="px-5 py-3 font-semibold">{{ $usage['qty'] }} {{ $consumable->unit }}</td><td class="px-5 py-3 text-gray-500">{{ $usage['user'] ?: 'System' }}</td></tr>@endforeach</tbody></table></div>@endif</div>
</div>
@endsection
