@extends('layouts.app')
@section('title', $tool->name)
@section('breadcrumb')<span class="text-gray-400">/</span><a href="{{ route('tools.index') }}" class="hover:text-gray-800">Tools</a><span class="text-gray-400">/</span><span class="text-gray-700 font-medium">{{ $tool->name }}</span>@endsection
@section('content')
@php
    $usageHistory = $tool->workOrderItems->map(fn($usage) => ['date' => $usage->used_at, 'source' => 'Work Order', 'reference' => $usage->workOrder?->wo_number, 'title' => $usage->workOrder?->title, 'url' => $usage->workOrder ? route('work-orders.show', $usage->workOrder) : null, 'user' => $usage->createdBy?->name])->merge($tool->maintenanceRecordTools->map(fn($usage) => ['date' => $usage->created_at, 'source' => 'Maintenance Record', 'reference' => $usage->maintenanceRecord?->record_number, 'title' => $usage->maintenanceRecord?->workOrder?->title, 'url' => $usage->maintenanceRecord ? route('maintenance-records.show', $usage->maintenanceRecord) : null, 'user' => $usage->maintenanceRecord?->technician?->name]))->sortByDesc('date');
@endphp
<div class="max-w-6xl space-y-5">
    <div class="flex items-center gap-3"><a href="{{ route('tools.index') }}" class="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg"><svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg></a><div><h1 class="text-2xl font-bold text-gray-900">{{ $tool->name }}</h1><p class="text-sm text-gray-500">{{ $tool->tool_code }} · {{ $tool->category ?: 'Tool' }}</p></div></div>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-5 items-start">
        <div class="bg-white rounded-xl border border-gray-200 shadow-sm p-6"><div class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-2 gap-4"><div><dt class="text-xs font-medium text-gray-500 uppercase">Kondisi</dt><dd class="mt-1 text-sm font-bold text-gray-900">{{ ucfirst($tool->condition) }}</dd></div><div><dt class="text-xs font-medium text-gray-500 uppercase">Tersedia</dt><dd class="mt-1 text-lg font-bold text-emerald-600">{{ $tool->qty_available }} / {{ $tool->qty_total }}</dd></div><div><dt class="text-xs font-medium text-gray-500 uppercase">Merek</dt><dd class="mt-1 text-sm text-gray-900">{{ $tool->brand ?: '—' }}</dd></div><div><dt class="text-xs font-medium text-gray-500 uppercase">Lokasi</dt><dd class="mt-1 text-sm text-gray-900">{{ $tool->location ?: '—' }}</dd></div></div>@if($tool->description)<p class="mt-5 pt-4 border-t border-gray-100 text-sm text-gray-700">{{ $tool->description }}</p>@endif</div>
        <div class="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden"><div class="px-5 py-4 border-b border-gray-100"><h2 class="font-semibold text-gray-900">Usage History</h2><p class="text-xs text-gray-500 mt-0.5">Riwayat tool yang dipakai pada pekerjaan.</p></div>@if($usageHistory->isEmpty())<p class="py-10 text-center text-sm text-gray-400">Belum ada histori pemakaian.</p>@else<div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-gray-50 text-xs font-semibold text-gray-500 uppercase"><th class="px-5 py-3 text-left">Tanggal</th><th class="px-5 py-3 text-left">Sumber</th><th class="px-5 py-3 text-left">Referensi</th><th class="px-5 py-3 text-left">Oleh</th></tr></thead><tbody class="divide-y divide-gray-50">@foreach($usageHistory as $usage)<tr><td class="px-5 py-3 text-gray-600">{{ $usage['date']?->format('d M Y H:i') }}</td><td class="px-5 py-3 text-gray-600">{{ $usage['source'] }}</td><td class="px-5 py-3 font-medium">@if($usage['url'])<a href="{{ $usage['url'] }}" class="text-brand hover:underline">{{ $usage['reference'] }}</a>@else{{ $usage['reference'] ?: '—' }}@endif @if($usage['title'])<span class="block text-xs text-gray-400">{{ $usage['title'] }}</span>@endif</td><td class="px-5 py-3 text-gray-500">{{ $usage['user'] ?: 'System' }}</td></tr>@endforeach</tbody></table></div>@endif</div>
    </div>
</div>
@endsection
